version: '3.8'

services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mockInterview
      MYSQL_USER: root
      MYSQL_PASSWORD: coderslab
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mockInterview?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: coderslab